# Deploy the Infrastructure using AWS Cloud Development Kit
name: Deploy - Infrastructure

on:
  push:
    branches: [ main ]
    paths: 
      - infrastructure/**/*
      - .github/workflows/deploy-infrastructure.yml
  pull_request:
    branches: [ main ]
    paths: 
      - infrastructure/**/*
      - .github/workflows/deploy-infrastructure.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: infrastructure

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      
      - name: Install Packages
        run: npm install
        
      - name: Transpile into Javascript
        run: npm run build
        
      - name: Run Unit Tests
        run: npm run test
        
      - name: Deploy to production
        run: |
          export BRANCH_NAME=${GITHUB_REF##*/}
          if [ "$BRANCH_NAME" == "main" ]; then
              npx cdk deploy --require-approval never
          else
              npx cdk deploy --require-approval never --parameters branchname="$BRANCH_NAME."
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
